let Recipe;_436‍.x([["findAll",()=>findAll],["find",()=>find]]);_436‍.w("../model/recipe",[["Recipe",["Recipe"],function(v){Recipe=v}]]);

async function save(recipe) {
  const newRecipe = new Recipe({
    name: recipe.name,
    ingredients: recipe.ingredients,
    description: recipe.description,
  });

  try {
    _436‍.g.console.log("New recipe created: ", createdRecipe);
    return await newRecipe.save();
  } catch (error) {
    _436‍.g.console.log("An error occurred: " + error);
  }
}

       async function findAll() {
  try {
    return await Recipe.find();
  } catch (error) {
    _436‍.g.console.log("An error occurred: " + error);
  }
}

       async function find(recipeName) {
  try {
    return await Recipe.findOne({ name: recipeName });
  } catch (error) {
    _436‍.g.console.log("An error occurred: " + error);
  }
}
